### ISSUE TITLE
Add Built Releases

### ISSUE THREAD

**Issue by mslinnea** [alleyinteractive/wp-alleyvate#96] opened 2024-06-20 20:47 UTC
### Description

This plugin requires dependencies to be built with composer, and will not work properly without the dependencies.

### Use Case

As a developer, I want to have a tagged release to download that already has the dependencies.

**Comment by srtfisher** [comment] 2024-12-16 21:15
Duplicate of #115

**Closed by srtfisher** 2024-12-16 21:15 UTC
Labels: enhancement
